In [1]:
#1. Read the bank.csv

#2. Perform the operations
         #head,tail,info,shape,isnull,isnull.sum()
#3. Perform the data types operations
#4. Seperate cat and num columns from scartch
#5. Sepertae cat and num columns using select dtypes

In [3]:
import numpy as nu
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv(r"C:\Users\Rao\Documents\Naresh IT\DATA FILES\bank.csv")

In [7]:
df.head()

  age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0  30;"unemployed";"married";"primary";"no";1787;...
1  33;"services";"married";"secondary";"no";4789;...
2  35;"management";"single";"tertiary";"no";1350;...
3  30;"management";"married";"tertiary";"no";1476...
4  59;"blue-collar";"married";"secondary";"no";0;...

In [9]:
df.tail()

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 1 columns):
 #   Column                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                --------------  -----
 0   age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"  4521 non-null   object
dtypes: object(1)
memory usage: 35.4+ KB

In [15]:
df.shape

(4521, 1)

In [19]:
df.isnull()

      age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0                                                 False
1                                                 False
2                                                 False
3                                                 False
4                                                 False
...                                                 ...
4516                                              False
4517                                              False
4518                                              False
4519                                              False
4520                                              False

[4521 rows x 1 columns]

In [21]:
df.isnull().sum()

age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"    0
dtype: int64

In [90]:
cols=df.dtypes.index.tolist()

In [92]:
dtype=df.dtypes.values.tolist()

In [94]:
num=[]
cat=[]
for i,j in zip(dtype,cols):
    if i=='object':
        cat.append(j)
    else:
        num.append(j)

In [96]:
cat

['age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"']

In [98]:
num

[]

In [100]:
cat=df.select_dtypes(include='object')

In [102]:
num=df.select_dtypes(exclude='object')